name = "GCMC_2D_Fluids"
uuid = "2542b8c8-34d7-4df2-85b1-2f0c8edc29aa"
authors = ["Felix Glitsch"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
